GET http://localhost:4000/events

###
GET http://localhost:3000/events/editable
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1NzgzNDA4MjIsImV4cCI6MTU3ODUxMzYyMiwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.H5oBhgzKPEZ9ZxJe0lJ7eNrLFvztIThgjrt2YmXl_nIg3wJbhV0ZzZLW5MNKAcyPI7-JVjCEl-74-GItl5PfrwRW-TZJa4g-kCR82i_o4Qf_IWq1kokPA7uNIZPz6JpFzMqy5c9qYic7IRrFbQPUbf9qH67GpYonI52NJMsIuYw



###
GET http://localhost:3000/events/5e2d8d10d92749d29faa7756

###

DELETE http://localhost:3000/events/5e2d8c14d92749d29faa7755
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1ODAwNDI4NTYsImV4cCI6MTU4MDIxNTY1NiwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.PhItxpQea69km0-gqr0ZtGiPEdf5IZSS_Qi2KnglBghqjzz0nj6GMG2LmvSu7UVGfu6KLC-OQiVnv3TQHMlaMTszW8kfdTGcDMGVMjmliWwV9SFtdnsoqgDrbih7elyfd2QdDB1wZSHQeiD1CK63yG0HPnzDW-S6hIPAunm0kCs

###

POST http://localhost:3000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1ODAwNDA2ODksImV4cCI6MTU4MDIxMzQ4OSwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.T0zAHtQR5WTal-LrZjALrl3BVBwLSeIr2FG4dMUbMwrsq2Xmx7uMLTlmHgsIKMZChX1_vgWiFJgNTMU_P_cTjLPC6E8V_CchnsPLbFJ1PB5NzIxKxFCMPGokGyB0mnl72_gL0Un-c3UqloHtkfunuzhrAqea2_Y-Mbza7Qo-0ws

{
      "name": "Les 10KM du Laerbeek",
      "description": "Les 10 kilomètres du Laerbeek est une course organisé au sein d'un des plus beau esapce vert de Bruxelles: le bois du Laerbeek. Le secrétariat pour le retrait des dossard est ouvert de 08:00 à 9:30 étant donné que le départ est donné à 10h dans le parc. Il y a un vestiaire pour les coureurs et la possibilité de se restaurer après l'épreuve.",
      "imgSrc": "https://i0.wp.com/www.joggans.be/wp-content/uploads/2019/06/LRX_3602.jpg",
      "distance": "10 km",
      "challenge": "Run in Brussels",
      "date": "2020-06-14T10:00:00Z",
      "accountNumber":"BE30 9730 7689 9311",
      "organization":"Joggans",
      "orgaUrl":"http://www.joggans.be/10km",
      "price":7
}


###
POST http://localhost:3000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1ODAwNDA2ODksImV4cCI6MTU4MDIxMzQ4OSwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.T0zAHtQR5WTal-LrZjALrl3BVBwLSeIr2FG4dMUbMwrsq2Xmx7uMLTlmHgsIKMZChX1_vgWiFJgNTMU_P_cTjLPC6E8V_CchnsPLbFJ1PB5NzIxKxFCMPGokGyB0mnl72_gL0Un-c3UqloHtkfunuzhrAqea2_Y-Mbza7Qo-0ws

{
      "name": "Les relais givrés",
      "description": "5 coureurs dont obligatoirement 1 dame et 1 vétéran (adulte de plus de 40 ans le jour de la course, donc né avant le 18/01/1980), parcourent chacun 8 km avant d'effectuer, groupés, un dernier tour de 4 km. Chaque équipe doit donc parcourir un total de 44 km.",
      "imgSrc": "https://o1.ldh.be/image/thumb/5a5dceb9cd7083db8b97b4ff.jpg",
      "distance": "12 km",
      "challenge": "Run in Brussels",
      "date": "2020-01-12T12:00:00Z",
      "accountNumber":"BE30 9730 7689 9311",
      "organization":"Les lendemain de la veille",
      "orgaUrl":"https://www.relaisgivres.be/index.php?option=com_content&view=article&id=14&Itemid=22&lang=fr#PRINCIPE_RG",
      "price":50
}

  //

###
PATCH http://localhost:3000/events/5e2d8d15d92749d29faa7757
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1ODAwNDA2ODksImV4cCI6MTU4MDIxMzQ4OSwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.T0zAHtQR5WTal-LrZjALrl3BVBwLSeIr2FG4dMUbMwrsq2Xmx7uMLTlmHgsIKMZChX1_vgWiFJgNTMU_P_cTjLPC6E8V_CchnsPLbFJ1PB5NzIxKxFCMPGokGyB0mnl72_gL0Un-c3UqloHtkfunuzhrAqea2_Y-Mbza7Qo-0ws

{
  "accountNumber":"BE74 9730 9544 5307",
}


###

PATCH http://ec2-34-253-189-132.eu-west-1.compute.amazonaws.com/api/events/5e495ec29b5d8e3e432a5c0a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTQ5NWMzZjliNWQ4ZTNlNDMyYTVjMDkiLCJpYXQiOjE1ODI0NjY4MzksImV4cCI6MTU4MjYzOTYzOSwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.JdNcY1580VAZQUo-EOt9MmqCcsYb1Yb5YhAneJGEPCABWw5cVDP5FNOrTEoNqfMQG4iwwAhgNW_rsaVl1s9EqC2eCAqPURm44XbYic2nF1L3KkckJIRZ03oU7y8B_O6jYd-w8wR6WOisY8nXEv9KBi2wH4MrPbXLkO77N6p5n80

{
 "accountNumber":"BE74 9730 9544 5307"
}

###

PATCH http://ec2-34-253-189-132.eu-west-1.compute.amazonaws.com/api/events/5e495ec29b5d8e3e432a5c0a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTQ5NWMzZjliNWQ4ZTNlNDMyYTVjMDkiLCJpYXQiOjE1ODI0NjY4MzksImV4cCI6MTU4MjYzOTYzOSwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.JdNcY1580VAZQUo-EOt9MmqCcsYb1Yb5YhAneJGEPCABWw5cVDP5FNOrTEoNqfMQG4iwwAhgNW_rsaVl1s9EqC2eCAqPURm44XbYic2nF1L3KkckJIRZ03oU7y8B_O6jYd-w8wR6WOisY8nXEv9KBi2wH4MrPbXLkO77N6p5n80

{
 "description":"Parcours boisé et vallonné de 10 km au sein du bois du Laerbeek, l’un des plus beaux espaces verts de Bruxelles.;Bosrijk en heuvelachtig parcours van 10 km in het Laarbeekbos, één van de mooiste groene zones van Brussel.|  • Pré-inscription / Pre-registartie: 7€ ⋙ Max 500 participants/deelnemers!;  • Dimanche 14 juin 2020 à 10 heures / Zondag 14 juni 2020 om 10u;  • Jogging Ganshoren – Rue au Bois – Bosstraat 11, 1083 Ganshoren;  • Retrait des dossards de 8h à 9h45 / Afhaling borstnummers vanaf 8u tot 9u45;  • Douches, Vestiaires, Consigne / Douches, Kleedkamers, Bewaarplaats;  • Tombola, musique, bar, petite restauration / Tombola, muziek, bar, kleine restauratie"
}