GET http://localhost:3000/events

###
GET http://localhost:3000/events/editable
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1NzgzNDA4MjIsImV4cCI6MTU3ODUxMzYyMiwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.H5oBhgzKPEZ9ZxJe0lJ7eNrLFvztIThgjrt2YmXl_nIg3wJbhV0ZzZLW5MNKAcyPI7-JVjCEl-74-GItl5PfrwRW-TZJa4g-kCR82i_o4Qf_IWq1kokPA7uNIZPz6JpFzMqy5c9qYic7IRrFbQPUbf9qH67GpYonI52NJMsIuYw

###
GET http://localhost:3000/events/5e107efc47328e7fa7300175

###

DELETE http://localhost:3000/events/5e178d2f1e712f99846151a8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1Nzg2MDE2NDgsImV4cCI6MTU3ODc3NDQ0OCwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.NYFONBk77aEQc9hD1NIBog422_SKwjEVkpUvq4xf1y86K5KRbUWv65eyIZQanDXLFbLFPyIA6PEqzz9vFDgCFOZiNA4PpAd2X64-jeTFV9Fmn8RxpFm6I88kOZeL0PoKNCsntlnQJplKiuAoxeBUeka-eVPN0NcpdyMvQq_WxMY

###
POST http://localhost:3000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1Nzg2MDE2NDgsImV4cCI6MTU3ODc3NDQ0OCwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.NYFONBk77aEQc9hD1NIBog422_SKwjEVkpUvq4xf1y86K5KRbUWv65eyIZQanDXLFbLFPyIA6PEqzz9vFDgCFOZiNA4PpAd2X64-jeTFV9Fmn8RxpFm6I88kOZeL0PoKNCsntlnQJplKiuAoxeBUeka-eVPN0NcpdyMvQq_WxMY

{
      "name": "Laerbeek",
      "description": "La dimanche 14 juin à 10h, le club Joggans organise un 10km dans le magnifique parc du Laerbeek. Le prix est de 7€ en pré-inscription.",
      "imageSrc": "https://i1.wp.com/www.joggans.be/wp-content/uploads/2017/06/DSC00138.jpg",
      "distance": "10km",
      "challenge": "Run in Brussels",
      "date": "2020-06-14T10:00:00Z",
      "accountNumber":"BE30 9730 7689 9311",
      "organization":"Joggans",
      "price":7
}

###
PATCH http://localhost:3000/events/5e0def2c32718a6b31a7c398
Content-Type: application/json 

{
  "name": "10KM Laerbeek"
}
