GET http://localhost:3000/subscribers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1ODAwNDA2ODksImV4cCI6MTU4MDIxMzQ4OSwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.T0zAHtQR5WTal-LrZjALrl3BVBwLSeIr2FG4dMUbMwrsq2Xmx7uMLTlmHgsIKMZChX1_vgWiFJgNTMU_P_cTjLPC6E8V_CchnsPLbFJ1PB5NzIxKxFCMPGokGyB0mnl72_gL0Un-c3UqloHtkfunuzhrAqea2_Y-Mbza7Qo-0ws

###

GET http://localhost:3000/subscribers/5e2d8d10d92749d29faa7756
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1ODAwNDA2ODksImV4cCI6MTU4MDIxMzQ4OSwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.T0zAHtQR5WTal-LrZjALrl3BVBwLSeIr2FG4dMUbMwrsq2Xmx7uMLTlmHgsIKMZChX1_vgWiFJgNTMU_P_cTjLPC6E8V_CchnsPLbFJ1PB5NzIxKxFCMPGokGyB0mnl72_gL0Un-c3UqloHtkfunuzhrAqea2_Y-Mbza7Qo-0ws


###

DELETE http://localhost:3000/subscribers/5e1398cc9bcdd98b5920c544

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "lastName": "Bobby",
  "firstName": "Lol",
  "gender": true,
  "email": "crappe.nicolas@gmail.com",
  "club": "Joggans",
  "challenge": true,
  "event_id": "5e2d8d10d92749d29faa7756",
  "birthDate": "1990-11-11",
  "postalCode": 1090
}

###
POST http://localhost:3000/subscribers/confirmation/5e178da77a2e1899b1f4819a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1Nzg2MDE2NDgsImV4cCI6MTU3ODc3NDQ0OCwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.NYFONBk77aEQc9hD1NIBog422_SKwjEVkpUvq4xf1y86K5KRbUWv65eyIZQanDXLFbLFPyIA6PEqzz9vFDgCFOZiNA4PpAd2X64-jeTFV9Fmn8RxpFm6I88kOZeL0PoKNCsntlnQJplKiuAoxeBUeka-eVPN0NcpdyMvQq_WxMY

[{"price":7, "structuredCom":"+++202/0111/12156+++"}]

###
PATCH http://localhost:3000/subscribers/5e0dc1dbb078c2688670a1e2
Content-Type: application/json 

{
  "name": "Tommy"
}

###
PATCH http://localhost:3000/subscribers/5e0dc1dbb078c2688670a1e2
Content-Type: application/json 

{
  "subscribedChannel": "Bob Channel"
}