POST http://localhost:3000/users/authenticate
Content-Type: application/json

{
  "email": "demo@gmail.com",
  "password": "Demo123"
}

###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "email": "demo@gmail.com",
  "firstName": "DemoFirst",
  "lastName": "DemoLast",
  "club":"Joggans",
  "password": "Demo123"
}

