POST https://ec2-34-253-189-132.eu-west-1.compute.amazonaws.com/api/users/authenticate
Content-Type: application/json

{
  "email": "joggansgroup@gmail.com",
  "password": "r8x146IEbedh_coN0zuj"
}

###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "email": "demo@gmail.com",
  "firstName": "DemoFirst",
  "lastName": "DemoLast",
  "club":"Joggans",
  "password": "Demo123"
}

