GET http://localhost:3000/events

###
GET http://localhost:3000/events/editable
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwODhjNzBlOWQ1MTgxM2I2ZTA1ZGIiLCJpYXQiOjE1NzgxNDE4OTYsImV4cCI6MTU3ODMxNDY5NiwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.SaE2PAW0gJ_5WHFd4zS5YzfyeSltb1xBUD6FXV2ZlbxpgIojmD8dWNd0xlKj76v_KM5Frv61haPet_eNWNojVYJkM3zcqubFqFC-ZfGyffFVobFtQ59O83kkxaWAj9WD3Aw4kNHnWv1oAK4gLXBoJ8sujmDOT3avyxwDf9D_TC8
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1NzgxMzkyNzAsImV4cCI6MTU3ODMxMjA3MCwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.NwSMqwH9IGtzGOLwKnBtX2_HyCg0T-4aggmWKtzSX_2PEjyZIrDqetlrZwxB325Au0N5Beu9v_JVYZFrjZP_l-_IOaIlVRN7jq-X4Im-CxrYJWxsmq3dnTyQHe9PCRGWkKudzue7MFtrlNzX337v1cxubdu4CSYOoUM4PGU_wj0

###
GET http://localhost:3000/events/5e0def2c32718a6b31a7c398

###

DELETE http://localhost:3000/events/5e107efc47328e7fa7300175
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwODhjNzBlOWQ1MTgxM2I2ZTA1ZGIiLCJpYXQiOjE1NzgxNDE4OTYsImV4cCI6MTU3ODMxNDY5NiwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.SaE2PAW0gJ_5WHFd4zS5YzfyeSltb1xBUD6FXV2ZlbxpgIojmD8dWNd0xlKj76v_KM5Frv61haPet_eNWNojVYJkM3zcqubFqFC-ZfGyffFVobFtQ59O83kkxaWAj9WD3Aw4kNHnWv1oAK4gLXBoJ8sujmDOT3avyxwDf9D_TC8
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1NzgxMzkyNzAsImV4cCI6MTU3ODMxMjA3MCwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.NwSMqwH9IGtzGOLwKnBtX2_HyCg0T-4aggmWKtzSX_2PEjyZIrDqetlrZwxB325Au0N5Beu9v_JVYZFrjZP_l-_IOaIlVRN7jq-X4Im-CxrYJWxsmq3dnTyQHe9PCRGWkKudzue7MFtrlNzX337v1cxubdu4CSYOoUM4PGU_wj0

###
POST http://localhost:3000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTEwN2M5MThmZWRjNzdmNjYxNWMxMDgiLCJpYXQiOjE1NzgxMzkyNzAsImV4cCI6MTU3ODMxMjA3MCwiYXVkIjoiaHR0cDovL3d3dy5qb2dnYW5zLmJlIiwiaXNzIjoiTmljb2xhcyBDcmFwcGUiLCJzdWIiOiJqb2dnYW5zZ3JvdXBAZ21haWwuY29tIn0.NwSMqwH9IGtzGOLwKnBtX2_HyCg0T-4aggmWKtzSX_2PEjyZIrDqetlrZwxB325Au0N5Beu9v_JVYZFrjZP_l-_IOaIlVRN7jq-X4Im-CxrYJWxsmq3dnTyQHe9PCRGWkKudzue7MFtrlNzX337v1cxubdu4CSYOoUM4PGU_wj0

{
      "name": "Laerbeek",
      "description": "La dimanche 14 juin à 10h, le club Joggans organise un 10km dans le magnifique parc du Laerbeek. Le prix est de 7€ en pré-inscription.",
      "imageSrc": "https://i1.wp.com/www.joggans.be/wp-content/uploads/2017/06/DSC00138.jpg",
      "distances": [ "10km", "5km" ],
      "challenges": ["Run in Brussels"],
      "date": "2020-06-14T10:00:00Z"
}

###
PATCH http://localhost:3000/events/5e0def2c32718a6b31a7c398
Content-Type: application/json 

{
  "name": "10KM Laerbeek"
}
