GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5e0db2894fcbd867a32385fc

###

DELETE http://localhost:3000/subscribers/5e0db2894fcbd867a32385fc

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Robert",
  "subscribedChannel": "Bennetts Channel"
}

###
PATCH http://localhost:3000/subscribers/5e0dc1dbb078c2688670a1e2
Content-Type: application/json 

{
  "name": "Tommy"
}